### ISSUE TITLE
[Readme Improvement] Please link to a description of what a arena is

### ISSUE THREAD

**Issue by anitamw** [cristicbz/sync-splitter#1]
Thanks!

**Comment by cristicbz** [comment]
Thanks for the issue! Could you submit a PR to link to something like https://stackoverflow.com/a/12825221 from the word `arena` in the README, please?

**Comment by anitamw** [comment]
ok! probably would have been quicker for you to do it since you found the link instead of replying here but it'd be an honour :P

**Comment by anitamw** [comment]
I didded it

**Comment by anitamw** [comment]
thank you for merging so quickly!
